name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3"]
        gemfile:
          - gemfiles/rails_7_2.gemfile
          - gemfiles/rails_8_0.gemfile
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter and tests
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: bundle exec rake
